from django.shortcuts import get_object_or_404,render,redirect
from django.http import HttpResponseRedirect, JsonResponse, HttpResponseServerError
from django.urls import reverse

from font.settings import MODEL_ROOT

from .models import Image
from .forms import ImageForm
from django.views.decorators.http import require_POST
import os
import tempfile

from matplotlib import pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow import keras
import cv2
import requests

from django_cleanup import cleanup



def index(request):
    return render(request, 'app/index.html')

def crop(request):
    form = ImageForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return JsonResponse({'massage': 'works'})
    context = {'form':form}
    return render(request, 'app/crop.html', context)


def result(request):
    name = np.array(['851MkPOP---Regular',
'BIZ UDGothic---Bold',
'BIZ UDGothic---Regular',
'BIZ UDMincho---Medium',
'Chogokuboso Gothic---Regular',
'FOT-Anito Std---Inline',
'FOT-Anito Std---L',
'FOT-Anito Std---M',
'FOT-Anito Std---Relief',
'FOT-AnticCezanne Pro---DB',
'FOT-AnticCezanne Pro---M',
'FOT-Aokane Std---EB',
'FOT-Aralet Std---DB',
'FOT-arc Std---R',
'FOT-Budo Std---L',
'FOT-Carat Std---UB',
'FOT-CezanneBokutoh Pro---B',
'FOT-CezanneBokutoh Pro---DB',
'FOT-CezanneBokutoh Pro---EB',
'FOT-CezanneBokutoh Pro---M',
'FOT-Cezanne Pro---B',
'FOT-Cezanne Pro---DB',
'FOT-Cezanne Pro---EB',
'FOT-Cezanne Pro---M',
'FOT-Cezanne ProN---B',
'FOT-Cezanne ProN---DB',
'FOT-Cezanne ProN---EB',
'FOT-Cezanne ProN---M',
'FOT-Chiaro Std---B',
'FOT-Comet Std---B',
'FOT-ComicMystery Std---DB',
'FOT-ComicReggae Std---B',
'FOT-CookHand Std---R',
'FOT-Cuckoo Std---B',
'FOT-DNPShuei4goBStd---Hv',
'FOT-DNPShuei4goStd---M',
'FOT-DNP ShueiAntiStd---B',
'FOT-DNP ShueiGoGinStd---B',
'FOT-DNP ShueiGoGinStd---L',
'FOT-DNP ShueiGoGinStd---M',
'FOT-DNP ShueiGoKinStd---B',
'FOT-DNP ShueiGoKinStd---L',
'FOT-DNP ShueiGoKinStd---M',
'FOT-DNP ShueiMGoStd---B',
'FOT-DNP ShueiMGoStd---L',
'FOT-DNPShueiMinPr6---B',
'FOT-DNPShueiMinPr6---L',
'FOT-DNPShueiMinPr6---M',
'FOT-DNPShueiMinPr6N---B',
'FOT-DNPShueiMinPr6N---L',
'FOT-DNPShueiMinPr6N---M',
'FOT-DNPShueiShogoMinStd---Hv',
'FOT-DNP ShueiYMinStd---B',
'FOT-DNP ShueiYMinStd---M',
'FOT-DotGothic12 Std---M',
'FOT-DotGothic16 Std---M',
'FOT-DotMincho12 Std---M',
'FOT-DotMincho16 Std---M',
'FOT-Gospel Std---EB',
'FOT-Greco Std---B',
'FOT-Greco Std---DB',
'FOT-Greco Std---M',
'FOT-Klee Pro---DB',
'FOT-Klee Pro---M',
'FOT-KsoAkebono---Regular',
'FOT-KsoBasakoro---Regular',
'FOT-KsoByakko---Regular',
'FOT-KsoFuraibou---Regular',
'FOT-KsoGenbu---Regular',
'FOT-KsoGinryu---Regular',
'FOT-KsoGokubutokaisho---Regular',
'FOT-KsoGoryuNew---Regular',
'FOT-KsoGyosho---Regular',
'FOT-KsoHannya---Regular',
'FOT-KsoHiryu---Regular',
'FOT-KsoJinba---Regular',
'FOT-KsoJukaku---Regular',
'FOT-KsoKaisho---Regular',
'FOT-KsoKanteiryu---Regular',
'FOT-KsoKouryu---Regular',
'FOT-KsoRaijin---Regular',
'FOT-KsoReisho---Regular',
'FOT-KsoShinryu---Regular',
'FOT-KsoYuai---Regular',
'FOT-Kurokane Std---EB',
'FOT-MatisseEleganto Pro---B',
'FOT-MatisseMinori Pro---B',
'FOT-Matisse Pro---EB',
'FOT-NewCezanne Pro---B',
'FOT-NewCezanne Pro---DB',
'FOT-NewCezanne Pro---EB',
'FOT-NewCezanne Pro---M',
'FOT-NewCezanne ProN---B',
'FOT-NewCezanne ProN---DB',
'FOT-NewCezanne ProN---EB',
'FOT-NewCezanne ProN---M',
'FOT-NewCinemaA Std---D',
'FOT-NewCinemaB Std---D',
'FOT-NewGreco Std---B',
'FOT-NewGreco Std---DB',
'FOT-NewGreco Std---M',
'FOT-NewGreco StdN---B',
'FOT-NewGreco StdN---DB',
'FOT-NewGreco StdN---M',
'FOT-NewRodin Pro---B',
'FOT-NewRodin Pro---DB',
'FOT-NewRodin Pro---L',
'FOT-NewRodin Pro---M',
'FOT-NewRodin Pro---UB',
'FOT-PopFury Std---B',
'FOT-PopHappiness Std---EB',
'FOT-PopJoy Std---B',
'FOT-Rodin Pro---B',
'FOT-Rodin Pro---DB',
'FOT-Rodin Pro---EB',
'FOT-Rodin Pro---L',
'FOT-Rodin Pro---M',
'FOT-SeuratCapie Pro---B',
'FOT-SeuratCapie Pro---DB',
'FOT-SeuratCapie Pro---EB',
'FOT-SeuratCapie Pro---M',
'FOT-Seurat Pro---B',
'FOT-Seurat Pro---DB',
'FOT-Seurat Pro---EB',
'FOT-Seurat Pro---L',
'FOT-Seurat Pro---M',
'FOT-Seurat Pro---UB',
'FOT-Seurat ProN---B',
'FOT-Seurat ProN---DB',
'FOT-Seurat ProN---EB',
'FOT-Seurat ProN---L',
'FOT-Seurat ProN---M',
'FOT-Seurat ProN---UB',
'FOT-Shadow Std---B',
'FOT-ShadowTL Std---B',
'FOT-Skip Pro---B',
'FOT-Skip Pro---D',
'FOT-Skip Pro---E',
'FOT-Skip Pro---L',
'FOT-Skip Pro---M',
'FOT-Skip ProN---B',
'FOT-Skip ProN---D',
'FOT-Skip ProN---E',
'FOT-Skip ProN---L',
'FOT-Skip ProN---M',
'FOT-Skip Std---B',
'FOT-Skip Std---D',
'FOT-Skip Std---E',
'FOT-Skip Std---L',
'FOT-Skip Std---M',
'FOT-Slump Std---DB',
'FOT-Steelwork Std---B',
'FOT-Stick Std---B',
'FOT-TelopMin Pro---B',
'FOT-TelopMin Pro---D',
'FOT-TelopMin Pro---E',
'FOT-TelopMin Pro---H',
'FOT-TelopMin ProN---B',
'FOT-TelopMin ProN---D',
'FOT-TelopMin ProN---E',
'FOT-TelopMin ProN---H',
'FOT-Tentomushi Std---L',
'FOT-Tsubame Std---R',
'FOT-TsukuAMDMin Std---E',
'FOT-TsukuAntiqueSGo Std---B',
'FOT-TsukuAOldMin Pr6---R',
'FOT-TsukuBMDMin Std---E',
'FOT-TsukuBMin Pr6---L',
'FOT-TsukuBOldMin Pr6---R',
'FOT-TsukuGo Pro---B',
'FOT-TsukuGo Pro---E',
'FOT-TsukuGo Pro---L',
'FOT-TsukuGo Pro---M',
'FOT-TsukuGo Pro---R',
'FOT-TsukuMin Pr5---B',
'FOT-TsukuMin Pr5---D',
'FOT-TsukuMin Pr5---R',
'FOT-TsukuOldMin Pro---R',
'FOT-UDKakugoC60 Pro---B',
'FOT-UDKakugoC60 Pro---DB',
'FOT-UDKakugoC60 Pro---L',
'FOT-UDKakugoC60 Pro---M',
'FOT-UDKakugoC60 Pro---R',
'FOT-UDKakugoC70 Pro---B',
'FOT-UDKakugoC70 Pro---DB',
'FOT-UDKakugoC70 Pro---L',
'FOT-UDKakugoC70 Pro---M',
'FOT-UDKakugoC70 Pro---R',
'FOT-UDKakugoC80 Pro---B',
'FOT-UDKakugoC80 Pro---DB',
'FOT-UDKakugoC80 Pro---L',
'FOT-UDKakugoC80 Pro---M',
'FOT-UDKakugoC80 Pro---R',
'FOT-UDKakugo_Large Pr6---B',
'FOT-UDKakugo_Large Pr6---DB',
'FOT-UDKakugo_Large Pr6---E',
'FOT-UDKakugo_Large Pr6---EL',
'FOT-UDKakugo_Large Pr6---H',
'FOT-UDKakugo_Large Pr6---L',
'FOT-UDKakugo_Large Pr6---M',
'FOT-UDKakugo_Large Pr6---R',
'FOT-UDKakugo_Large Pr6---U',
'FOT-UDKakugo_Large Pr6---UL',
'FOT-UDKakugo_Large Pr6N---B',
'FOT-UDKakugo_Large Pr6N---DB',
'FOT-UDKakugo_Large Pr6N---E',
'FOT-UDKakugo_Large Pr6N---EL',
'FOT-UDKakugo_Large Pr6N---H',
'FOT-UDKakugo_Large Pr6N---L',
'FOT-UDKakugo_Large Pr6N---M',
'FOT-UDKakugo_Large Pr6N---R',
'FOT-UDKakugo_Large Pr6N---U',
'FOT-UDKakugo_Large Pr6N---UL',
'FOT-UDKakugo_Large Pro---B',
'FOT-UDKakugo_Large Pro---DB',
'FOT-UDKakugo_Large Pro---L',
'FOT-UDKakugo_Large Pro---M',
'FOT-UDKakugo_Large Pro---R',
'FOT-UDKakugo_Small Pr6---B',
'FOT-UDKakugo_Small Pr6---DB',
'FOT-UDKakugo_Small Pr6---E',
'FOT-UDKakugo_Small Pr6---EL',
'FOT-UDKakugo_Small Pr6---H',
'FOT-UDKakugo_Small Pr6---L',
'FOT-UDKakugo_Small Pr6---M',
'FOT-UDKakugo_Small Pr6---R',
'FOT-UDKakugo_Small Pr6---U',
'FOT-UDKakugo_Small Pr6---UL',
'FOT-UDKakugo_Small Pr6N---B',
'FOT-UDKakugo_Small Pr6N---DB',
'FOT-UDKakugo_Small Pr6N---E',
'FOT-UDKakugo_Small Pr6N---EL',
'FOT-UDKakugo_Small Pr6N---H',
'FOT-UDKakugo_Small Pr6N---L',
'FOT-UDKakugo_Small Pr6N---M',
'FOT-UDKakugo_Small Pr6N---R',
'FOT-UDKakugo_Small Pr6N---U',
'FOT-UDKakugo_Small Pr6N---UL',
'FOT-UDMarugo_Large Pr6---B',
'FOT-UDMarugo_Large Pr6---DB',
'FOT-UDMarugo_Large Pr6---E',
'FOT-UDMarugo_Large Pr6---H',
'FOT-UDMarugo_Large Pr6---L',
'FOT-UDMarugo_Large Pr6---M',
'FOT-UDMarugo_Large Pr6---U',
'FOT-UDMarugo_Large Pr6N---B',
'FOT-UDMarugo_Large Pr6N---DB',
'FOT-UDMarugo_Large Pr6N---E',
'FOT-UDMarugo_Large Pr6N---H',
'FOT-UDMarugo_Large Pr6N---L',
'FOT-UDMarugo_Large Pr6N---M',
'FOT-UDMarugo_Large Pr6N---U',
'FOT-UDMarugo_Large Pro---B',
'FOT-UDMarugo_Large Pro---DB',
'FOT-UDMarugo_Large Pro---L',
'FOT-UDMarugo_Large Pro---M',
'FOT-UDMarugo_Small Pr6---B',
'FOT-UDMarugo_Small Pr6---DB',
'FOT-UDMarugo_Small Pr6---E',
'FOT-UDMarugo_Small Pr6---H',
'FOT-UDMarugo_Small Pr6---L',
'FOT-UDMarugo_Small Pr6---M',
'FOT-UDMarugo_Small Pr6---U',
'FOT-UDMarugo_Small Pr6N---B',
'FOT-UDMarugo_Small Pr6N---DB',
'FOT-UDMarugo_Small Pr6N---E',
'FOT-UDMarugo_Small Pr6N---H',
'FOT-UDMarugo_Small Pr6N---L',
'FOT-UDMarugo_Small Pr6N---M',
'FOT-UDMarugo_Small Pr6N---U',
'FOT-UDMincho Pr6---B',
'FOT-UDMincho Pr6---DB',
'FOT-UDMincho Pr6---L',
'FOT-UDMincho Pr6---M',
'FOT-UDMincho Pr6N---B',
'FOT-UDMincho Pr6N---DB',
'FOT-UDMincho Pr6N---L',
'FOT-UDMincho Pr6N---M',
'FOT-UDMincho Pro---B',
'FOT-UDMincho Pro---DB',
'FOT-UDMincho Pro---L',
'FOT-UDMincho Pro---M',
'FOT-Yuruka Std---UB',
'HGGothicE---Regular',
'HGGothicM---Medium',
'HGGyoshotai---Medium',
'HGKyokashotai---Medium',
'HGMinchoB---Bold',
'HGMinchoE---Regular',
'HGSoeiKakupoptai---Regular',
'HGSoeiPresenceEB---Extra-Bold',
'HGSoeiKakugothicUB---Regular',
'HGSeikaishotaiPRO---Regular',
'HGMaruGothicMPRO---Regular',
'IPAexGothic---Regular',
'IPAexMincho---Regular',
'Meiryo---Regular',
'Meiryo---Bold',
'M PLUS 1---Regular',
'Source Han Sans JP---Bold',
'Source Han Sans JP---ExtraLight',
'Source Han Sans JP---Heavy',
'Source Han Sans JP---Light',
'Source Han Sans JP---Medium',
'Source Han Sans JP---Normal',
'Source Han Sans JP---Regular',
'Source Han Serif JP---Bold',
'Source Han Serif JP---ExtraLight',
'Source Han Serif JP---Heavy',
'Source Han Serif JP---Light',
'Source Han Serif JP---Medium',
'Source Han Serif JP---Regular',
'Source Han Serif JP---SemiBold',
'UD Digi Kyokasho N-B---Bold',
'UD Digi Kyokasho N-R---Regular',
'Yu Gothic---Bold',
'Yu Gothic---Light',
'Yu Gothic---Medium',
'Yu Gothic---Regular',
'Yu Mincho---Regular',
'Yu Mincho---Demibold',
'Yu Mincho---Light',
'cotorifont-Pro-L-OT---Regular'
],dtype=object)

    path = 'https://res.cloudinary.com/hriscwqpd/image/upload/v1639740962/my-image.png'

    image = imread_web(path)
    image = cv2.resize(image,dsize=(224,224))
    image = image/255.0
    test_image = (np.expand_dims(image,0))
    model = tf.keras.models.load_model(MODEL_ROOT)
    predictions = model.predict(test_image)
    predictions_sort = np.argsort(predictions[0])[::-1]
    name_sort = name[predictions_sort]
    result_sort = predictions[0][predictions_sort]

    context = {
        'name':name_sort,
        'result':result_sort,
    }
    return render(request, 'app/result.html',context)

def imread_web(url):
    # 画像をリクエストする
    res = requests.get(url)
    img = None
    # Tempfileを作成して即読み込む
    fp = tempfile.NamedTemporaryFile(dir='./', delete=False)
    fp.write(res.content)
    fp.close()
    img = cv2.imread(fp.name)
    os.remove(fp.name)
    return img
